/**
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.modelDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Member</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.netappsid.configurator.modelDsl.EnumMember#getName <em>Name</em>}</li>
 *   <li>{@link com.netappsid.configurator.modelDsl.EnumMember#getImagePath <em>Image Path</em>}</li>
 *   <li>{@link com.netappsid.configurator.modelDsl.EnumMember#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see com.netappsid.configurator.modelDsl.ModelDslPackage#getEnumMember()
 * @model
 * @generated
 */
public interface EnumMember extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.netappsid.configurator.modelDsl.ModelDslPackage#getEnumMember_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.netappsid.configurator.modelDsl.EnumMember#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Image Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Image Path</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Image Path</em>' attribute.
   * @see #setImagePath(String)
   * @see com.netappsid.configurator.modelDsl.ModelDslPackage#getEnumMember_ImagePath()
   * @model
   * @generated
   */
  String getImagePath();

  /**
   * Sets the value of the '{@link com.netappsid.configurator.modelDsl.EnumMember#getImagePath <em>Image Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Image Path</em>' attribute.
   * @see #getImagePath()
   * @generated
   */
  void setImagePath(String value);

  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link com.netappsid.configurator.modelDsl.EnumFieldValue}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Values</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see com.netappsid.configurator.modelDsl.ModelDslPackage#getEnumMember_Values()
   * @model containment="true"
   * @generated
   */
  EList<EnumFieldValue> getValues();

} // EnumMember
