/**
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.modelDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.netappsid.configurator.modelDsl.Enum#getFields <em>Fields</em>}</li>
 *   <li>{@link com.netappsid.configurator.modelDsl.Enum#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see com.netappsid.configurator.modelDsl.ModelDslPackage#getEnum()
 * @model
 * @generated
 */
public interface Enum extends PackageMember
{
  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link com.netappsid.configurator.modelDsl.EnumField}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fields</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see com.netappsid.configurator.modelDsl.ModelDslPackage#getEnum_Fields()
   * @model containment="true"
   * @generated
   */
  EList<EnumField> getFields();

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link com.netappsid.configurator.modelDsl.EnumMember}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Members</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see com.netappsid.configurator.modelDsl.ModelDslPackage#getEnum_Members()
   * @model containment="true"
   * @generated
   */
  EList<EnumMember> getMembers();

} // Enum
