/**
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.modelDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.netappsid.configurator.modelDsl.ModelDslFactory
 * @model kind="package"
 * @generated
 */
public interface ModelDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "modelDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.netappsid.com/configurator/ModelDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "modelDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ModelDslPackage eINSTANCE = com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl.init();

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.ModelImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__IMPORT_SECTION = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.PackageMemberImpl <em>Package Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.PackageMemberImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getPackageMember()
   * @generated
   */
  int PACKAGE_MEMBER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_MEMBER__NAME = 0;

  /**
   * The number of structural features of the '<em>Package Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_MEMBER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.PackageDeclarationImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getPackageDeclaration()
   * @generated
   */
  int PACKAGE_DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__NAME = PACKAGE_MEMBER__NAME;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__ELEMENTS = PACKAGE_MEMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Package Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION_FEATURE_COUNT = PACKAGE_MEMBER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.ConfigurableImpl <em>Configurable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.ConfigurableImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getConfigurable()
   * @generated
   */
  int CONFIGURABLE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURABLE__NAME = PACKAGE_MEMBER__NAME;

  /**
   * The feature id for the '<em><b>Abstract</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURABLE__ABSTRACT = PACKAGE_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURABLE__SUPER_TYPE = PACKAGE_MEMBER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURABLE__PROPERTIES = PACKAGE_MEMBER_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Configurable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURABLE_FEATURE_COUNT = PACKAGE_MEMBER_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.PropertyImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = 1;

  /**
   * The feature id for the '<em><b>Default Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__DEFAULT_VALUE = 2;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__ATTRIBUTES = 3;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.DefaultValueImpl <em>Default Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.DefaultValueImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getDefaultValue()
   * @generated
   */
  int DEFAULT_VALUE = 5;

  /**
   * The feature id for the '<em><b>Default Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT_VALUE__DEFAULT_VALUE = 0;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT_VALUE__UNIT = 1;

  /**
   * The number of structural features of the '<em>Default Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT_VALUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.AttributeImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.EnumImpl <em>Enum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.EnumImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getEnum()
   * @generated
   */
  int ENUM = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM__NAME = PACKAGE_MEMBER__NAME;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM__FIELDS = PACKAGE_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM__MEMBERS = PACKAGE_MEMBER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Enum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_FEATURE_COUNT = PACKAGE_MEMBER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.EnumFieldImpl <em>Enum Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.EnumFieldImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getEnumField()
   * @generated
   */
  int ENUM_FIELD = 8;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_FIELD__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_FIELD__NAME = 1;

  /**
   * The number of structural features of the '<em>Enum Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_FIELD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.EnumMemberImpl <em>Enum Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.EnumMemberImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getEnumMember()
   * @generated
   */
  int ENUM_MEMBER = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_MEMBER__NAME = 0;

  /**
   * The feature id for the '<em><b>Image Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_MEMBER__IMAGE_PATH = 1;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_MEMBER__VALUES = 2;

  /**
   * The number of structural features of the '<em>Enum Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_MEMBER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.EnumFieldValueImpl <em>Enum Field Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.EnumFieldValueImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getEnumFieldValue()
   * @generated
   */
  int ENUM_FIELD_VALUE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_FIELD_VALUE__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_FIELD_VALUE__VALUE = 1;

  /**
   * The number of structural features of the '<em>Enum Field Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_FIELD_VALUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.DynamicEnumImpl <em>Dynamic Enum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.DynamicEnumImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getDynamicEnum()
   * @generated
   */
  int DYNAMIC_ENUM = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DYNAMIC_ENUM__NAME = PACKAGE_MEMBER__NAME;

  /**
   * The feature id for the '<em><b>Table Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DYNAMIC_ENUM__TABLE_NAME = PACKAGE_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DYNAMIC_ENUM__COLUMNS = PACKAGE_MEMBER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Image Column</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DYNAMIC_ENUM__IMAGE_COLUMN = PACKAGE_MEMBER_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Dynamic Enum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DYNAMIC_ENUM_FEATURE_COUNT = PACKAGE_MEMBER_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.netappsid.configurator.modelDsl.impl.DynamicEnumColumnImpl <em>Dynamic Enum Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netappsid.configurator.modelDsl.impl.DynamicEnumColumnImpl
   * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getDynamicEnumColumn()
   * @generated
   */
  int DYNAMIC_ENUM_COLUMN = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DYNAMIC_ENUM_COLUMN__NAME = 0;

  /**
   * The feature id for the '<em><b>Column Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DYNAMIC_ENUM_COLUMN__COLUMN_INDEX = 1;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DYNAMIC_ENUM_COLUMN__LABEL = 2;

  /**
   * The number of structural features of the '<em>Dynamic Enum Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DYNAMIC_ENUM_COLUMN_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.netappsid.configurator.modelDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link com.netappsid.configurator.modelDsl.Model#getImportSection <em>Import Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Import Section</em>'.
   * @see com.netappsid.configurator.modelDsl.Model#getImportSection()
   * @see #getModel()
   * @generated
   */
  EReference getModel_ImportSection();

  /**
   * Returns the meta object for the containment reference list '{@link com.netappsid.configurator.modelDsl.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.netappsid.configurator.modelDsl.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.PackageDeclaration <em>Package Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Declaration</em>'.
   * @see com.netappsid.configurator.modelDsl.PackageDeclaration
   * @generated
   */
  EClass getPackageDeclaration();

  /**
   * Returns the meta object for the containment reference list '{@link com.netappsid.configurator.modelDsl.PackageDeclaration#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.netappsid.configurator.modelDsl.PackageDeclaration#getElements()
   * @see #getPackageDeclaration()
   * @generated
   */
  EReference getPackageDeclaration_Elements();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.PackageMember <em>Package Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Member</em>'.
   * @see com.netappsid.configurator.modelDsl.PackageMember
   * @generated
   */
  EClass getPackageMember();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.PackageMember#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netappsid.configurator.modelDsl.PackageMember#getName()
   * @see #getPackageMember()
   * @generated
   */
  EAttribute getPackageMember_Name();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.Configurable <em>Configurable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configurable</em>'.
   * @see com.netappsid.configurator.modelDsl.Configurable
   * @generated
   */
  EClass getConfigurable();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.Configurable#isAbstract <em>Abstract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Abstract</em>'.
   * @see com.netappsid.configurator.modelDsl.Configurable#isAbstract()
   * @see #getConfigurable()
   * @generated
   */
  EAttribute getConfigurable_Abstract();

  /**
   * Returns the meta object for the containment reference '{@link com.netappsid.configurator.modelDsl.Configurable#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Super Type</em>'.
   * @see com.netappsid.configurator.modelDsl.Configurable#getSuperType()
   * @see #getConfigurable()
   * @generated
   */
  EReference getConfigurable_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link com.netappsid.configurator.modelDsl.Configurable#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see com.netappsid.configurator.modelDsl.Configurable#getProperties()
   * @see #getConfigurable()
   * @generated
   */
  EReference getConfigurable_Properties();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see com.netappsid.configurator.modelDsl.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the containment reference '{@link com.netappsid.configurator.modelDsl.Property#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see com.netappsid.configurator.modelDsl.Property#getType()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Type();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.Property#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netappsid.configurator.modelDsl.Property#getName()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.netappsid.configurator.modelDsl.Property#getDefaultValue <em>Default Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Default Value</em>'.
   * @see com.netappsid.configurator.modelDsl.Property#getDefaultValue()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_DefaultValue();

  /**
   * Returns the meta object for the containment reference list '{@link com.netappsid.configurator.modelDsl.Property#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see com.netappsid.configurator.modelDsl.Property#getAttributes()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Attributes();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.DefaultValue <em>Default Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Default Value</em>'.
   * @see com.netappsid.configurator.modelDsl.DefaultValue
   * @generated
   */
  EClass getDefaultValue();

  /**
   * Returns the meta object for the containment reference '{@link com.netappsid.configurator.modelDsl.DefaultValue#getDefaultValue <em>Default Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Default Value</em>'.
   * @see com.netappsid.configurator.modelDsl.DefaultValue#getDefaultValue()
   * @see #getDefaultValue()
   * @generated
   */
  EReference getDefaultValue_DefaultValue();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.DefaultValue#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see com.netappsid.configurator.modelDsl.DefaultValue#getUnit()
   * @see #getDefaultValue()
   * @generated
   */
  EAttribute getDefaultValue_Unit();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see com.netappsid.configurator.modelDsl.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netappsid.configurator.modelDsl.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.netappsid.configurator.modelDsl.Attribute#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.netappsid.configurator.modelDsl.Attribute#getExpression()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Expression();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.Enum <em>Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum</em>'.
   * @see com.netappsid.configurator.modelDsl.Enum
   * @generated
   */
  EClass getEnum();

  /**
   * Returns the meta object for the containment reference list '{@link com.netappsid.configurator.modelDsl.Enum#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see com.netappsid.configurator.modelDsl.Enum#getFields()
   * @see #getEnum()
   * @generated
   */
  EReference getEnum_Fields();

  /**
   * Returns the meta object for the containment reference list '{@link com.netappsid.configurator.modelDsl.Enum#getMembers <em>Members</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Members</em>'.
   * @see com.netappsid.configurator.modelDsl.Enum#getMembers()
   * @see #getEnum()
   * @generated
   */
  EReference getEnum_Members();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.EnumField <em>Enum Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Field</em>'.
   * @see com.netappsid.configurator.modelDsl.EnumField
   * @generated
   */
  EClass getEnumField();

  /**
   * Returns the meta object for the containment reference '{@link com.netappsid.configurator.modelDsl.EnumField#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see com.netappsid.configurator.modelDsl.EnumField#getType()
   * @see #getEnumField()
   * @generated
   */
  EReference getEnumField_Type();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.EnumField#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netappsid.configurator.modelDsl.EnumField#getName()
   * @see #getEnumField()
   * @generated
   */
  EAttribute getEnumField_Name();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.EnumMember <em>Enum Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Member</em>'.
   * @see com.netappsid.configurator.modelDsl.EnumMember
   * @generated
   */
  EClass getEnumMember();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.EnumMember#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netappsid.configurator.modelDsl.EnumMember#getName()
   * @see #getEnumMember()
   * @generated
   */
  EAttribute getEnumMember_Name();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.EnumMember#getImagePath <em>Image Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Image Path</em>'.
   * @see com.netappsid.configurator.modelDsl.EnumMember#getImagePath()
   * @see #getEnumMember()
   * @generated
   */
  EAttribute getEnumMember_ImagePath();

  /**
   * Returns the meta object for the containment reference list '{@link com.netappsid.configurator.modelDsl.EnumMember#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see com.netappsid.configurator.modelDsl.EnumMember#getValues()
   * @see #getEnumMember()
   * @generated
   */
  EReference getEnumMember_Values();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.EnumFieldValue <em>Enum Field Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Field Value</em>'.
   * @see com.netappsid.configurator.modelDsl.EnumFieldValue
   * @generated
   */
  EClass getEnumFieldValue();

  /**
   * Returns the meta object for the reference '{@link com.netappsid.configurator.modelDsl.EnumFieldValue#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see com.netappsid.configurator.modelDsl.EnumFieldValue#getName()
   * @see #getEnumFieldValue()
   * @generated
   */
  EReference getEnumFieldValue_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.netappsid.configurator.modelDsl.EnumFieldValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see com.netappsid.configurator.modelDsl.EnumFieldValue#getValue()
   * @see #getEnumFieldValue()
   * @generated
   */
  EReference getEnumFieldValue_Value();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.DynamicEnum <em>Dynamic Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dynamic Enum</em>'.
   * @see com.netappsid.configurator.modelDsl.DynamicEnum
   * @generated
   */
  EClass getDynamicEnum();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.DynamicEnum#getTableName <em>Table Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Table Name</em>'.
   * @see com.netappsid.configurator.modelDsl.DynamicEnum#getTableName()
   * @see #getDynamicEnum()
   * @generated
   */
  EAttribute getDynamicEnum_TableName();

  /**
   * Returns the meta object for the containment reference list '{@link com.netappsid.configurator.modelDsl.DynamicEnum#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns</em>'.
   * @see com.netappsid.configurator.modelDsl.DynamicEnum#getColumns()
   * @see #getDynamicEnum()
   * @generated
   */
  EReference getDynamicEnum_Columns();

  /**
   * Returns the meta object for the reference '{@link com.netappsid.configurator.modelDsl.DynamicEnum#getImageColumn <em>Image Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Image Column</em>'.
   * @see com.netappsid.configurator.modelDsl.DynamicEnum#getImageColumn()
   * @see #getDynamicEnum()
   * @generated
   */
  EReference getDynamicEnum_ImageColumn();

  /**
   * Returns the meta object for class '{@link com.netappsid.configurator.modelDsl.DynamicEnumColumn <em>Dynamic Enum Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dynamic Enum Column</em>'.
   * @see com.netappsid.configurator.modelDsl.DynamicEnumColumn
   * @generated
   */
  EClass getDynamicEnumColumn();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.DynamicEnumColumn#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netappsid.configurator.modelDsl.DynamicEnumColumn#getName()
   * @see #getDynamicEnumColumn()
   * @generated
   */
  EAttribute getDynamicEnumColumn_Name();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.DynamicEnumColumn#getColumnIndex <em>Column Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column Index</em>'.
   * @see com.netappsid.configurator.modelDsl.DynamicEnumColumn#getColumnIndex()
   * @see #getDynamicEnumColumn()
   * @generated
   */
  EAttribute getDynamicEnumColumn_ColumnIndex();

  /**
   * Returns the meta object for the attribute '{@link com.netappsid.configurator.modelDsl.DynamicEnumColumn#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see com.netappsid.configurator.modelDsl.DynamicEnumColumn#getLabel()
   * @see #getDynamicEnumColumn()
   * @generated
   */
  EAttribute getDynamicEnumColumn_Label();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ModelDslFactory getModelDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.ModelImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Import Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__IMPORT_SECTION = eINSTANCE.getModel_ImportSection();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.PackageDeclarationImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getPackageDeclaration()
     * @generated
     */
    EClass PACKAGE_DECLARATION = eINSTANCE.getPackageDeclaration();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE_DECLARATION__ELEMENTS = eINSTANCE.getPackageDeclaration_Elements();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.PackageMemberImpl <em>Package Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.PackageMemberImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getPackageMember()
     * @generated
     */
    EClass PACKAGE_MEMBER = eINSTANCE.getPackageMember();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE_MEMBER__NAME = eINSTANCE.getPackageMember_Name();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.ConfigurableImpl <em>Configurable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.ConfigurableImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getConfigurable()
     * @generated
     */
    EClass CONFIGURABLE = eINSTANCE.getConfigurable();

    /**
     * The meta object literal for the '<em><b>Abstract</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURABLE__ABSTRACT = eINSTANCE.getConfigurable_Abstract();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURABLE__SUPER_TYPE = eINSTANCE.getConfigurable_SuperType();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURABLE__PROPERTIES = eINSTANCE.getConfigurable_Properties();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.PropertyImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__TYPE = eINSTANCE.getProperty_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__NAME = eINSTANCE.getProperty_Name();

    /**
     * The meta object literal for the '<em><b>Default Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__DEFAULT_VALUE = eINSTANCE.getProperty_DefaultValue();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__ATTRIBUTES = eINSTANCE.getProperty_Attributes();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.DefaultValueImpl <em>Default Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.DefaultValueImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getDefaultValue()
     * @generated
     */
    EClass DEFAULT_VALUE = eINSTANCE.getDefaultValue();

    /**
     * The meta object literal for the '<em><b>Default Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFAULT_VALUE__DEFAULT_VALUE = eINSTANCE.getDefaultValue_DefaultValue();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFAULT_VALUE__UNIT = eINSTANCE.getDefaultValue_Unit();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.AttributeImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__EXPRESSION = eINSTANCE.getAttribute_Expression();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.EnumImpl <em>Enum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.EnumImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getEnum()
     * @generated
     */
    EClass ENUM = eINSTANCE.getEnum();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM__FIELDS = eINSTANCE.getEnum_Fields();

    /**
     * The meta object literal for the '<em><b>Members</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM__MEMBERS = eINSTANCE.getEnum_Members();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.EnumFieldImpl <em>Enum Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.EnumFieldImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getEnumField()
     * @generated
     */
    EClass ENUM_FIELD = eINSTANCE.getEnumField();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM_FIELD__TYPE = eINSTANCE.getEnumField_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_FIELD__NAME = eINSTANCE.getEnumField_Name();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.EnumMemberImpl <em>Enum Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.EnumMemberImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getEnumMember()
     * @generated
     */
    EClass ENUM_MEMBER = eINSTANCE.getEnumMember();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_MEMBER__NAME = eINSTANCE.getEnumMember_Name();

    /**
     * The meta object literal for the '<em><b>Image Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_MEMBER__IMAGE_PATH = eINSTANCE.getEnumMember_ImagePath();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM_MEMBER__VALUES = eINSTANCE.getEnumMember_Values();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.EnumFieldValueImpl <em>Enum Field Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.EnumFieldValueImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getEnumFieldValue()
     * @generated
     */
    EClass ENUM_FIELD_VALUE = eINSTANCE.getEnumFieldValue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM_FIELD_VALUE__NAME = eINSTANCE.getEnumFieldValue_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM_FIELD_VALUE__VALUE = eINSTANCE.getEnumFieldValue_Value();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.DynamicEnumImpl <em>Dynamic Enum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.DynamicEnumImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getDynamicEnum()
     * @generated
     */
    EClass DYNAMIC_ENUM = eINSTANCE.getDynamicEnum();

    /**
     * The meta object literal for the '<em><b>Table Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DYNAMIC_ENUM__TABLE_NAME = eINSTANCE.getDynamicEnum_TableName();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DYNAMIC_ENUM__COLUMNS = eINSTANCE.getDynamicEnum_Columns();

    /**
     * The meta object literal for the '<em><b>Image Column</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DYNAMIC_ENUM__IMAGE_COLUMN = eINSTANCE.getDynamicEnum_ImageColumn();

    /**
     * The meta object literal for the '{@link com.netappsid.configurator.modelDsl.impl.DynamicEnumColumnImpl <em>Dynamic Enum Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netappsid.configurator.modelDsl.impl.DynamicEnumColumnImpl
     * @see com.netappsid.configurator.modelDsl.impl.ModelDslPackageImpl#getDynamicEnumColumn()
     * @generated
     */
    EClass DYNAMIC_ENUM_COLUMN = eINSTANCE.getDynamicEnumColumn();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DYNAMIC_ENUM_COLUMN__NAME = eINSTANCE.getDynamicEnumColumn_Name();

    /**
     * The meta object literal for the '<em><b>Column Index</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DYNAMIC_ENUM_COLUMN__COLUMN_INDEX = eINSTANCE.getDynamicEnumColumn_ColumnIndex();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DYNAMIC_ENUM_COLUMN__LABEL = eINSTANCE.getDynamicEnumColumn_Label();

  }

} //ModelDslPackage
