/**
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.validation;

import com.netappsid.configurator.modelDsl.Configurable;
import com.netappsid.configurator.modelDsl.ModelDslPackage;
import com.netappsid.configurator.validation.AbstractModelDslValidator;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ModelDslValidator extends AbstractModelDslValidator {
  @Check(CheckType.FAST)
  public void checkConfigurableNameStartsWithCapital(final Configurable conf) {
    String _name = conf.getName();
    char _charAt = _name.charAt(0);
    boolean _isUpperCase = Character.isUpperCase(_charAt);
    boolean _not = (!_isUpperCase);
    if (_not) {
      this.error("Name shall start with a capital", conf, ModelDslPackage.Literals.ATTRIBUTE__NAME);
    }
  }
}
