/**
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.modelDsl.impl;

import com.netappsid.configurator.modelDsl.Attribute;
import com.netappsid.configurator.modelDsl.Configurable;
import com.netappsid.configurator.modelDsl.DefaultValue;
import com.netappsid.configurator.modelDsl.DynamicEnum;
import com.netappsid.configurator.modelDsl.DynamicEnumColumn;
import com.netappsid.configurator.modelDsl.EnumField;
import com.netappsid.configurator.modelDsl.EnumFieldValue;
import com.netappsid.configurator.modelDsl.EnumMember;
import com.netappsid.configurator.modelDsl.Model;
import com.netappsid.configurator.modelDsl.ModelDslFactory;
import com.netappsid.configurator.modelDsl.ModelDslPackage;
import com.netappsid.configurator.modelDsl.PackageDeclaration;
import com.netappsid.configurator.modelDsl.PackageMember;
import com.netappsid.configurator.modelDsl.Property;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ModelDslFactoryImpl extends EFactoryImpl implements ModelDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ModelDslFactory init()
  {
    try
    {
      ModelDslFactory theModelDslFactory = (ModelDslFactory)EPackage.Registry.INSTANCE.getEFactory(ModelDslPackage.eNS_URI);
      if (theModelDslFactory != null)
      {
        return theModelDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ModelDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModelDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ModelDslPackage.MODEL: return createModel();
      case ModelDslPackage.PACKAGE_DECLARATION: return createPackageDeclaration();
      case ModelDslPackage.PACKAGE_MEMBER: return createPackageMember();
      case ModelDslPackage.CONFIGURABLE: return createConfigurable();
      case ModelDslPackage.PROPERTY: return createProperty();
      case ModelDslPackage.DEFAULT_VALUE: return createDefaultValue();
      case ModelDslPackage.ATTRIBUTE: return createAttribute();
      case ModelDslPackage.ENUM: return createEnum();
      case ModelDslPackage.ENUM_FIELD: return createEnumField();
      case ModelDslPackage.ENUM_MEMBER: return createEnumMember();
      case ModelDslPackage.ENUM_FIELD_VALUE: return createEnumFieldValue();
      case ModelDslPackage.DYNAMIC_ENUM: return createDynamicEnum();
      case ModelDslPackage.DYNAMIC_ENUM_COLUMN: return createDynamicEnumColumn();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PackageDeclaration createPackageDeclaration()
  {
    PackageDeclarationImpl packageDeclaration = new PackageDeclarationImpl();
    return packageDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PackageMember createPackageMember()
  {
    PackageMemberImpl packageMember = new PackageMemberImpl();
    return packageMember;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Configurable createConfigurable()
  {
    ConfigurableImpl configurable = new ConfigurableImpl();
    return configurable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Property createProperty()
  {
    PropertyImpl property = new PropertyImpl();
    return property;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DefaultValue createDefaultValue()
  {
    DefaultValueImpl defaultValue = new DefaultValueImpl();
    return defaultValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute createAttribute()
  {
    AttributeImpl attribute = new AttributeImpl();
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public com.netappsid.configurator.modelDsl.Enum createEnum()
  {
    EnumImpl enum_ = new EnumImpl();
    return enum_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnumField createEnumField()
  {
    EnumFieldImpl enumField = new EnumFieldImpl();
    return enumField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnumMember createEnumMember()
  {
    EnumMemberImpl enumMember = new EnumMemberImpl();
    return enumMember;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnumFieldValue createEnumFieldValue()
  {
    EnumFieldValueImpl enumFieldValue = new EnumFieldValueImpl();
    return enumFieldValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DynamicEnum createDynamicEnum()
  {
    DynamicEnumImpl dynamicEnum = new DynamicEnumImpl();
    return dynamicEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DynamicEnumColumn createDynamicEnumColumn()
  {
    DynamicEnumColumnImpl dynamicEnumColumn = new DynamicEnumColumnImpl();
    return dynamicEnumColumn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModelDslPackage getModelDslPackage()
  {
    return (ModelDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ModelDslPackage getPackage()
  {
    return ModelDslPackage.eINSTANCE;
  }

} //ModelDslFactoryImpl
