/**
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.web;

import com.google.inject.Provider;
import com.netappsid.configurator.web.AbstractModelDslWebModule;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ModelDslWebModule extends AbstractModelDslWebModule {
  public ModelDslWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
