/**
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import com.netappsid.configurator.ModelDslRuntimeModule;
import com.netappsid.configurator.ModelDslStandaloneSetup;
import com.netappsid.configurator.web.ModelDslWebModule;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ModelDslWebSetup extends ModelDslStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final ModelDslRuntimeModule runtimeModule = new ModelDslRuntimeModule();
    final ModelDslWebModule webModule = new ModelDslWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public ModelDslWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
