/*
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractModelDslScopeProvider extends XbaseBatchScopeProvider {
}
