/*
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.ui;

import com.google.inject.Injector;
import com.netappsid.configurator.dsl.model.ui.internal.ModelActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ModelDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ModelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ModelActivator.getInstance().getInjector(ModelActivator.COM_NETAPPSID_CONFIGURATOR_MODELDSL);
	}
	
}
