/**
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.ui.contentassist;

import com.netappsid.configurator.ui.contentassist.AbstractModelDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ModelDslProposalProvider extends AbstractModelDslProposalProvider {
}
