/*
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.validation

import com.netappsid.configurator.modelDsl.Configurable
import org.eclipse.xtext.validation.Check
import com.netappsid.configurator.modelDsl.ModelDslPackage

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ModelDslValidator extends AbstractModelDslValidator {

	@Check(FAST)
	def checkConfigurableNameStartsWithCapital(Configurable conf) {
		if (!Character.isUpperCase(conf.name.charAt(0))) {
			error('Name shall start with a capital', conf, ModelDslPackage.Literals.ATTRIBUTE__NAME);
		}
	}

}
