/*
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ModelDslStandaloneSetup extends ModelDslStandaloneSetupGenerated {

	def static void doSetup() {
		new ModelDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
