/*
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModelDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/netappsid/configurator/parser/antlr/internal/InternalModelDsl.tokens");
	}
}
