/*
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.parser.antlr;

import com.google.inject.Inject;
import com.netappsid.configurator.parser.antlr.internal.InternalModelDslParser;
import com.netappsid.configurator.services.ModelDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ModelDslParser extends AbstractAntlrParser {

	@Inject
	private ModelDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalModelDslParser createParser(XtextTokenStream stream) {
		return new InternalModelDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ModelDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ModelDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
