/**
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator;

import com.netappsid.configurator.ModelDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModelDslStandaloneSetup extends ModelDslStandaloneSetupGenerated {
  public static void doSetup() {
    ModelDslStandaloneSetup _modelDslStandaloneSetup = new ModelDslStandaloneSetup();
    _modelDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
