/*
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.ui.tests;

import com.google.inject.Injector;
import com.netappsid.configurator.dsl.model.ui.internal.ModelActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class ModelDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ModelActivator.getInstance().getInjector("com.netappsid.configurator.ModelDsl");
	}

}
