/**
 * generated by Xtext 2.9.1
 */
package com.netappsid.configurator.ui;

import com.netappsid.configurator.ui.AbstractModelDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ModelDslUiModule extends AbstractModelDslUiModule {
  public ModelDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
